version: "3.9"
services:
  backend:
    build: ./server
    ports:
      - "4000:4000"
    env_file:
      - ./server/.env
    depends_on:
      - mysql
    volumes:
      - ./server:/app
    restart: always

  mysql:
    image: mysql:8
    container_name: mysql_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: mydb
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

volumes:
  mysql-data: